// Generated by gencpp from file joycon/pub_val.msg
// DO NOT EDIT!


#ifndef JOYCON_MESSAGE_PUB_VAL_H
#define JOYCON_MESSAGE_PUB_VAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace joycon
{
template <class ContainerAllocator>
struct pub_val_
{
  typedef pub_val_<ContainerAllocator> Type;

  pub_val_()
    : theta(0)
    , r(0)  {
    }
  pub_val_(const ContainerAllocator& _alloc)
    : theta(0)
    , r(0)  {
  (void)_alloc;
    }



   typedef int32_t _theta_type;
  _theta_type theta;

   typedef int32_t _r_type;
  _r_type r;





  typedef boost::shared_ptr< ::joycon::pub_val_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::joycon::pub_val_<ContainerAllocator> const> ConstPtr;

}; // struct pub_val_

typedef ::joycon::pub_val_<std::allocator<void> > pub_val;

typedef boost::shared_ptr< ::joycon::pub_val > pub_valPtr;
typedef boost::shared_ptr< ::joycon::pub_val const> pub_valConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::joycon::pub_val_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::joycon::pub_val_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace joycon

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'joycon': ['/home/ando/catkin_ws/src/joycon/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::joycon::pub_val_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::joycon::pub_val_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::joycon::pub_val_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::joycon::pub_val_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::joycon::pub_val_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::joycon::pub_val_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::joycon::pub_val_<ContainerAllocator> >
{
  static const char* value()
  {
    return "58427f44aac94a7705da0eb1e5227372";
  }

  static const char* value(const ::joycon::pub_val_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x58427f44aac94a77ULL;
  static const uint64_t static_value2 = 0x05da0eb1e5227372ULL;
};

template<class ContainerAllocator>
struct DataType< ::joycon::pub_val_<ContainerAllocator> >
{
  static const char* value()
  {
    return "joycon/pub_val";
  }

  static const char* value(const ::joycon::pub_val_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::joycon::pub_val_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 theta\n\
int32 r\n\
";
  }

  static const char* value(const ::joycon::pub_val_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::joycon::pub_val_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.theta);
      stream.next(m.r);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pub_val_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::joycon::pub_val_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::joycon::pub_val_<ContainerAllocator>& v)
  {
    s << indent << "theta: ";
    Printer<int32_t>::stream(s, indent + "  ", v.theta);
    s << indent << "r: ";
    Printer<int32_t>::stream(s, indent + "  ", v.r);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JOYCON_MESSAGE_PUB_VAL_H
