// Generated by gencpp from file custom_msg/Nineaxis_sensor.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSG_MESSAGE_NINEAXIS_SENSOR_H
#define CUSTOM_MSG_MESSAGE_NINEAXIS_SENSOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace custom_msg
{
template <class ContainerAllocator>
struct Nineaxis_sensor_
{
  typedef Nineaxis_sensor_<ContainerAllocator> Type;

  Nineaxis_sensor_()
    : accl()
    , gyro()
    , mag()  {
    }
  Nineaxis_sensor_(const ContainerAllocator& _alloc)
    : accl(_alloc)
    , gyro(_alloc)
    , mag(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _accl_type;
  _accl_type accl;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _gyro_type;
  _gyro_type gyro;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _mag_type;
  _mag_type mag;





  typedef boost::shared_ptr< ::custom_msg::Nineaxis_sensor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msg::Nineaxis_sensor_<ContainerAllocator> const> ConstPtr;

}; // struct Nineaxis_sensor_

typedef ::custom_msg::Nineaxis_sensor_<std::allocator<void> > Nineaxis_sensor;

typedef boost::shared_ptr< ::custom_msg::Nineaxis_sensor > Nineaxis_sensorPtr;
typedef boost::shared_ptr< ::custom_msg::Nineaxis_sensor const> Nineaxis_sensorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msg::Nineaxis_sensor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msg::Nineaxis_sensor_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace custom_msg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'custom_msg': ['/home/ando/zyugyourobokon/src/custom_msg/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::custom_msg::Nineaxis_sensor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msg::Nineaxis_sensor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msg::Nineaxis_sensor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msg::Nineaxis_sensor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msg::Nineaxis_sensor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msg::Nineaxis_sensor_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msg::Nineaxis_sensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f88f64117d491e110b918a22793ff2a1";
  }

  static const char* value(const ::custom_msg::Nineaxis_sensor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf88f64117d491e11ULL;
  static const uint64_t static_value2 = 0x0b918a22793ff2a1ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msg::Nineaxis_sensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msg/Nineaxis_sensor";
  }

  static const char* value(const ::custom_msg::Nineaxis_sensor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msg::Nineaxis_sensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Vector3 accl\n\
geometry_msgs/Vector3 gyro\n\
geometry_msgs/Vector3 mag\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::custom_msg::Nineaxis_sensor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msg::Nineaxis_sensor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.accl);
      stream.next(m.gyro);
      stream.next(m.mag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Nineaxis_sensor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msg::Nineaxis_sensor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msg::Nineaxis_sensor_<ContainerAllocator>& v)
  {
    s << indent << "accl: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.accl);
    s << indent << "gyro: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.gyro);
    s << indent << "mag: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.mag);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSG_MESSAGE_NINEAXIS_SENSOR_H
