// Generated by gencpp from file shagailaunch/shagailaunch_msg.msg
// DO NOT EDIT!


#ifndef SHAGAILAUNCH_MESSAGE_SHAGAILAUNCH_MSG_H
#define SHAGAILAUNCH_MESSAGE_SHAGAILAUNCH_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace shagailaunch
{
template <class ContainerAllocator>
struct shagailaunch_msg_
{
  typedef shagailaunch_msg_<ContainerAllocator> Type;

  shagailaunch_msg_()
    : phase(0)
    , action()  {
    }
  shagailaunch_msg_(const ContainerAllocator& _alloc)
    : phase(0)
    , action(_alloc)  {
  (void)_alloc;
    }



   typedef int8_t _phase_type;
  _phase_type phase;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _action_type;
  _action_type action;





  typedef boost::shared_ptr< ::shagailaunch::shagailaunch_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::shagailaunch::shagailaunch_msg_<ContainerAllocator> const> ConstPtr;

}; // struct shagailaunch_msg_

typedef ::shagailaunch::shagailaunch_msg_<std::allocator<void> > shagailaunch_msg;

typedef boost::shared_ptr< ::shagailaunch::shagailaunch_msg > shagailaunch_msgPtr;
typedef boost::shared_ptr< ::shagailaunch::shagailaunch_msg const> shagailaunch_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::shagailaunch::shagailaunch_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::shagailaunch::shagailaunch_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace shagailaunch

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'shagailaunch': ['/home/ando/catkin_ws/src/shagaiLaunch/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::shagailaunch::shagailaunch_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::shagailaunch::shagailaunch_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::shagailaunch::shagailaunch_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::shagailaunch::shagailaunch_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::shagailaunch::shagailaunch_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::shagailaunch::shagailaunch_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::shagailaunch::shagailaunch_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5d4369385089c16dc86085a13d1749a8";
  }

  static const char* value(const ::shagailaunch::shagailaunch_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5d4369385089c16dULL;
  static const uint64_t static_value2 = 0xc86085a13d1749a8ULL;
};

template<class ContainerAllocator>
struct DataType< ::shagailaunch::shagailaunch_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "shagailaunch/shagailaunch_msg";
  }

  static const char* value(const ::shagailaunch::shagailaunch_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::shagailaunch::shagailaunch_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 phase\n\
string action\n\
";
  }

  static const char* value(const ::shagailaunch::shagailaunch_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::shagailaunch::shagailaunch_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.phase);
      stream.next(m.action);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct shagailaunch_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::shagailaunch::shagailaunch_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::shagailaunch::shagailaunch_msg_<ContainerAllocator>& v)
  {
    s << indent << "phase: ";
    Printer<int8_t>::stream(s, indent + "  ", v.phase);
    s << indent << "action: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.action);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SHAGAILAUNCH_MESSAGE_SHAGAILAUNCH_MSG_H
